before_install:
- sudo rm -f /etc/mavenrc
- export M2_HOME=/usr/local/maven
- export MAVEN_OPTS="-Dmaven.repo.local=$HOME/.m2/repository -Xms1024m -Xmx3072m"
jdk:
- oraclejdk8
language: java
sudo: required

addons:
  sonarcloud:
    organization: "hashmapinc-github" # the key of the org you chose at step #3
    token:
        secure: "fcoReZvq0MHb2zLRkvWIZyvdApJRUcoalErrylo5B2SZ/Vg7Bbc1seCo5sbb/K02f+CdpompnRKtSDP0ULadxSIHZZMZZwV9Gm2xMiwNdlJ63xqE40SF8w24gL3s2RSL/udmc+lPHBMtmWt9nVfXfyUWt429jnNRJB+e8zYqEgSip9iKVjiaDM8ZfJ8RqR0Fz0ZTvhlPa33NDCszhIDsactxAW8yTkXxZ0IQ1MDyAdQ7AiGc+y7w0Iq+XFH9BKwBCXY7KbEwaESz9Hc4UtJcobS960d1fWklJNAUQplZQ3sS3Ga68Nvnwm5MmYUP1PWL7wDURTewf54xgWuRJ5hYRXUzHAMKDQyMxcYCYqg50Q40w5hJHKet1wctX5gr9CXvOH6JR9SlZGsqjVH/tVxZdDvcFm10MlNLHntREiTybdc7kNnRBCDdNTlUs2A68/fXQtl0agl82Y5hxf+qbczTFqnUE2lW2LbLgDL2whmhrwnMvoiy6Bt8srWaHGsQ9U5O5AhpPOW0eIoloHWpj/ZilDdpkNznkpG80BeByhIt2fMoGP2tFRtyElnscio+LXJialov7XJLr2WjM9J1Hz2irYoLACg6z3cojtkLKrWYJIKTAtqgmePp/pWkEkCPR+mzLVz8dsK5EO0z41YD8HM1n9CQ0UqqLXhtpYBvWH9O4Ww="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -DskipTests
