apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  ports:
    - name: psql
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.6
        imagePullPolicy: Always
        env:
        - name: POSTGRES_DB
          value: "tempus"
        ports:
        - containerPort: 5432
          name: psql
#        command: [ "postgres" ]
#        command: [ "psql -U postgres -W postgres" ]
#        command: [ "/bin/bash", "-c", "--" ]
#        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: ebs-gp2
